# Basic site settings
title: "Scholarn Theme"
description: "An online platform for education."
baseurl: "/theme"
url: "https://scholarn.github.io"
theme: minima
author: Md Azaharuddin
permalink: pretty
timezone: "Asia/Kolkata"  # For example, "Asia/Kolkata"
defaults:
  - 
    scope:
      path: ""
    values:
      layout: default
collections:
  courses:
    output: true
  lessons:
    output: true
  units:
    output: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
