# Basic site settings
title: "Scholarn Theme"
description: "An online platform for education."
baseurl: "/theme"
url: "https://scholarn.github.io"
theme: minima
author:
  name: Md Azaharuddin
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
