# Basic site settings
title: "Scholarn Theme"
description: "An online platform for education."
baseurl: "/theme"
url: "https://scholarn.github.io/theme"
theme: minima
author:
  name: Md Azaharuddin

minima:
  skin: dark
